apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-app
  template:
    metadata:
      labels:
        app: crash-app
    spec:
      containers:
      - name: crash-container
        image: busybox
        command: ["/bin/sh", "-c", "echo 'Crashing...'; exit 1"]
