apiVersion: v1
kind: Service
metadata:
  name: simple-kube-web-app
spec:
  selector:
    app: simple-kube-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
